flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: 100%
      - type: patch
        target: 100%
  individual_flags:
    - name: prisma-factory
      paths:
        - packages/prisma-factory
      carryforward: true
      statuses:
        - type: project
          target: 95%
        - type: patch
          target: 100%
