version: "3.9"
services:
  prisma_factory_db:
    image: postgres:17.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
