name: lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  run-lint:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Setup pnpm
        uses: pnpm/action-setup@23657c8550e9be4f7ee7e9d7fe8adda6d703bb4e

      - name: Setup node.js
        uses: actions/setup-node@eff380dfbcf941bf8832e4acb788cebe13dfd758
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run secretlint
        run: pnpm run secretlint

      - name: Run format
        run: pnpm run format

      - name: Run type-check
        run: pnpm exec turbo run type-check

      - name: Run lint
        run: pnpm run lint
